# Generated by Django 5.2.5 on 2025-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='email',
            field=models.EmailField(default='anshika@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
