# Generated by Django 5.2.5 on 2025-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
