# Generated by Django 5.2.5 on 2025-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_found_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='location',
            field=models.CharField(default='demo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='location',
            field=models.CharField(default='demo', max_length=200),
            preserve_default=False,
        ),
    ]
