# Generated by Django 5.2.5 on 2025-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_found_location_lost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='photo',
            field=models.ImageField(blank=True, upload_to='founds/'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='losts/'),
        ),
    ]
