# Generated by Django 5.2.5 on 2025-08-19 18:30

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_found_photo_alter_lost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='photo',
            field=models.ImageField(blank=True, upload_to=myapp.models.path_founds),
        ),
        migrations.AlterField(
            model_name='lost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=myapp.models.path_losts),
        ),
    ]
